
test2:test2_7
	echo "Make success!"

test2_1 : test2_1.c
	gcc -o test2_1 test2_1.c

test2_2 : test2_2.c
	gcc -o test2_2 test2_2.c

test2_3 : test2_3.c
	gcc -o test2_3 test2_3.c

test2_4 : test2_4.c
	gcc -o test2_4 test2_4.c 

test2_5 : test2_5.c
	gcc -o test2_5 test2_5.c 

test2_6 : test2_6.c
	gcc -o test2_6 test2_6.c 

test2_7 : test2_7.c
	gcc -o test2_7 test2_7.c 

test2_8 : test2_8.c
	gcc -o test2_8 test2_8.c 

test2_9 : test2_9.c
	gcc -o test2_9 test2_9.c 

test2_10 : test2_10.c
	gcc -o test2_10 test2_10.c 

test2_11 : test2_11.c
	gcc -o test2_11 test2_11.c 

test2_12 : test2_12.c
	gcc -o test2_12 test2_12.c 

clean:
	rm -rf test2_? *.tar
